# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
name: nupic.torch
channels:
  - defaults

dependencies:
  - python=3.6
  - pip

  - pip:
      # Install nupic.torch in develop mode
      - -r requirements-dev.txt
      - -e . --no-binary :all

